#!/usr/bin/env php
<?php 

define('PROJECT_ROOT',__DIR__) ;
foreach (glob(__DIR__ . "/src/lib/*.php") as $file) { require_once $file; }
$loader = require_once __DIR__ . '/vendor/autoload.php' ;

$app = new GR\GR($argv) ;
$exit_code = $app->run() ;
exit($exit_code);
